# Generated by Django 3.0.7 on 2023-11-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231026_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='nombre_cliente',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo_empresa',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
