# Generated by Django 3.0.7 on 2023-11-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231108_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='correo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='nombre_empresa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='nombre_usuario',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_suscripcion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
