# Generated by Django 3.0.7 on 2023-11-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20231115_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='nombre_empresa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='nombre_empresa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
