# Generated by Django 3.0.7 on 2023-11-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231122_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tipo_empresa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
