# Generated by Django 3.0.7 on 2023-11-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contrato_tipo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='nombre_empresa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
