# Generated by Django 3.0.7 on 2023-11-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_capacitacion_nombre_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_termino',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
